name: Setup ansible
description: Setup ansible for vms

inputs:
  ssh_private_key:
    description: 'SSH private key, base64 encoded'
    required: true
  known_hosts:
    description: 'SSH known hosts'
    required: true
  vm_host:
    description: 'VM address'
    required: true
  vm_user:
    description: 'VM user'
    required: true

runs:
  using: composite
  steps:
  - name: Checkout repo
    uses: actions/checkout@v4
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: "3.13"
  - name: Setup ansible
    shell: bash
    run: pipx install --include-deps ansible
  - name: Install ansible collections
    shell: bash
    run: ansible-galaxy collection install -r requirements.yml
  - name: Setup SSH
    shell: bash
    run: |
      eval `ssh-agent -s`
      mkdir -p ~/.ssh/
      touch ~/.ssh/id_ed25519
      echo -e "${{ inputs.ssh_private_key }}" | base64 -d | tr -d '\r' > ~/.ssh/id_ed25519
      chmod 700 ~/.ssh/id_ed25519
      echo -r "${{ inputs.known_hosts }}" > ~/.ssh/known_hosts
  - name: Create inventory
    shell: bash
    run: |
      cat > ansible/inventory.ini << EOF
      [vms]
      ${{ inputs.vm_host }} ansible_user=${{ inputs.vm_user }} 
      EOF