- name: Docker image build
  hosts: vms
  become: true
  vars:
    docker_user: "{{ lookup('env', 'DOCKER_USER') }}"
    image_name: "{{ docker_user }}/{{ lookup('env', 'DOCKER_IMAGE_NAME') }}"
    image_tag: "{{ lookup('env', 'CI_COMMIT_TAG') }}"
    docker_pass: "{{ lookup('env', 'DOCKER_TOKEN') }}"
    source_path: ./app
  tasks:
    - name: Copy source container
      ansible.posix.synchronize:
        src: ../../app/
        dest: "{{ source_path }}"
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=dist"

    - name: Build image
      community.docker.docker_image_build:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        path: "{{ source_path }}"

    - name: Remove source code
      ansible.builtin.file:
        path: "{{ source_path }}"
        state: absent

    - name: Login to registry
      community.docker.docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_pass }}"
        reauthorize: true

    - name: Push image
      community.docker.docker_image_push:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"

    - name: Prune docker build cache
      community.docker.docker_prune:
        builder_cache: true
