- name: Update compose
  hosts: vms
  become: true
  vars:
    env_path: "{{ lookup('env', 'ENV', default='../../compose/.env') }}"
    back_image: adel160505/dashboard-itis-backend:latest
    docker_user: "{{ lookup('env', 'DOCKER_USER') }}"
    image_name: "{{ docker_user }}/{{ lookup('env', 'DOCKER_IMAGE_NAME') }}"
    image_tag: "{{ lookup('env', 'CI_COMMIT_TAG') }}" 
    front_image: "{{ image_name }}:{{ image_tag }}"
    compose_path: ./compose.yaml
  tasks:
    - name: Copy .env
      ansible.builtin.copy:
        src: "{{ env_path }}"
        dest: ./.env
        mode: preserve

    - name: Check if compose exists
      ansible.builtin.stat:
        path: "{{ compose_path }}"
      register: file_data

    - name: Stop containers
      community.docker.docker_compose_v2:
        project_src: .
        state: absent
        remove_orphans: true
      when: file_data.stat.exists

    - name: Read compose file
      ansible.builtin.slurp:
        src: "{{ compose_path }}"
      when: file_data.stat.exists
      register: yaml_data

    - name: Parse data
      ansible.builtin.set_fact:
        compose_data: "{{ yaml_data.content | b64decode | from_yaml }}"
      when: file_data.stat.exists

    - name: Extract backend image
      ansible.builtin.set_fact:
        back_image: "{{ compose_data['x-back-image'] }}"
      when: file_data.stat.exists

    - name: Make a template
      ansible.builtin.template:
        src: ../compose.j2
        dest: "{{ compose_path }}"
        mode: preserve

    - name: Start compose
      community.docker.docker_compose_v2:
        project_src: .
        state: present

    - name: Prune unused
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: false
