name: Release workflow
on:
  push:
    branches:
      - main
      - ci-cd
permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Run semantic
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v6
        with:
          working_directory: ./app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      new_release: ${{ steps.semantic_release.outputs.new_release_version }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: dashboard-itis/frontend.github/actions/ansible-setup@ci-cd
        with:
          ssh_private_key: ${{  secrets.SSH_PRIVATE_KEY_B64 }}
          known_hosts: ${{  secrets.SSH_KNOWN_HOSTS }}
          vm_host: ${{  secrets.VM_HOST }}
          vm_user: ${{  secrets.VM_USER }}
      - name: Run build playbook
        run: |
          cd ansible
          ansible-playbook \
            -i inventory.ini \
            playbooks/build-image-playbook.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_FORCE_COLOR: "true"
          DOCKER_USER: ${{ vars.DOCKER_USER }}
          DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          CI_COMMIT_TAG: ${{ needs.release.outputs.new_release }}-gh-front
      - name: Copy .env
        env:
          ENV_FILE: ${{ secrets.ENV }}
        run: printenv ENV_FILE > ~/.env
      - name: Run compose update playbook
        run: |
          cd ansible
          ansible-playbook \
            -i inventory.ini \
            playbooks/update-compose-playbook.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_FORCE_COLOR: "true"
          DOCKER_USER: ${{ vars.DOCKER_USER }}
          DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
          CI_COMMIT_TAG: ${{ needs.release.outputs.new_release }}-gh-front
          ENV: ~/.env

      

